services:
  - type: web
    name: valentine-site
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    plan: free

    routes:
      - type: rewrite
        source: /*
        destination: /index.html

